# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Xilinx/Project/200t/AM_modulation/AM_modulation.srcs/sources_1/ip/mult/mult.xci
# IP: The module: 'mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Project/200t/AM_modulation/AM_modulation.gen/sources_1/ip/mult/mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Xilinx/Project/200t/AM_modulation/AM_modulation.srcs/sources_1/ip/mult/mult.xci
# IP: The module: 'mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Project/200t/AM_modulation/AM_modulation.gen/sources_1/ip/mult/mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
