# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Xilinx/Project/200t/AM_modulation/AM_modulation.srcs/sources_1/ip/sin_rom/sin_rom.xci
# IP: The module: 'sin_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Project/200t/AM_modulation/AM_modulation.gen/sources_1/ip/sin_rom/sin_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sin_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Xilinx/Project/200t/AM_modulation/AM_modulation.srcs/sources_1/ip/sin_rom/sin_rom.xci
# IP: The module: 'sin_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Project/200t/AM_modulation/AM_modulation.gen/sources_1/ip/sin_rom/sin_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sin_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
